version: 2
updates:
  # Rust dependencies
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "tapsilat"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
      include: "scope"
